project:
  type: book

## Global options that can be re-defined in each qmd file
format:
  html:
    toc: true
    theme: [simplex, aml4td.scss]
    mainfont: 'Libre Franklin'
    fig-width: 6
    fig-height: 4.25
    fig-align: center
    tbl-cap-location: bottom
    fig-cap-location: bottom
    keep-md: false

crossref:
  custom:
    - kind: float
      reference-prefix: Algorithm
      key: alg

execute:
  freeze: auto
  keep-md: false
  # turn these on during development
  # message: false
  # warning: false
  echo: false


## Define book style and declare qmd files to process
book:
  title: "Hover-over names"
  author:
  - name: Max Kuhn
  date: last-modified
  date-format: YYYY-MM-DD
  sidebar:
      style: "docked"
      title: " "
  reader-mode: true
  bread-crumbs: false
  chapters:
  - index.qmd

bibliography: references.bib
csl: chicago-author-date-inline.csl

